# Generated by Django 5.1.6 on 2025-02-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employeeregistration'),
        ('service_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.PositiveIntegerField()),
                ('max_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeregistration')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_manager.service')),
            ],
        ),
    ]
