# Generated by Django 5.1.6 on 2025-02-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_manager', '0002_serviceregistry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceregistry',
            old_name='service',
            new_name='service_name',
        ),
    ]
