# Generated by Django 5.1.6 on 2025-02-14 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_manager', '0003_rename_service_serviceregistry_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistry',
            name='subservice_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_manager.subservice'),
        ),
    ]
