# Generated by Django 5.1.6 on 2025-02-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_manager', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_set', to='service_manager.subservice'),
        ),
    ]
